insert into `optionitem` (`id`, `type`, `name`) VALUES (0, 0, 'Tấn công+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (1, 0, 'Thời gian sử dụng # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (2, 0, 'HP, KI+#000');
insert into `optionitem` (`id`, `type`, `name`) VALUES (3, 0, 'Vô hiệu và biến #% sát thương chưởng thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (4, 0, 'Hồi phục #% KI khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (5, 0, '+#% sức đánh chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (6, 1, 'HP+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (7, 1, 'KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (8, 1, 'Hút #% HP, KI xung quanh mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (9, 1, 'Hiệu lực trong # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (10, 1, 'Sát thương chuẩn #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (11, 2, 'Công đức +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (12, 2, 'Số lần sử dụng còn lại +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (13, 2, 'Số yêu quái đã hạ +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (14, 2, 'Chí mạng+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (15, 2, 'Phản đòn cận chiến+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (16, 2, 'Tốc độ di chuyển+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (17, 2, 'Né đòn: +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (18, 2, 'Chính xác: +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (19, 2, 'Tấn công+#% khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (20, 2, 'PIN #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (21, 2, 'Yêu cầu sức mạnh # tỉ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (22, 2, 'HP+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (23, 2, 'KI+#K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (24, 2, 'Làm tăng trọng lực, gây chậm mọi người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (25, 2, 'Tàng hình mỗi 5 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (26, 2, 'Hóa đá mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (27, 2, '+# HP/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (28, 2, '+# KI/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (29, 5, 'Biến Sôcôla mọi người xung quanh mỗi 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (30, 0, 'Không giao dịch');
insert into `optionitem` (`id`, `type`, `name`) VALUES (31, 0, 'Số lượng #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (32, 0, 'Không bị hóa Xương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (33, 6, 'Dịch chuyển tức thời');
insert into `optionitem` (`id`, `type`, `name`) VALUES (34, 6, 'Tinh ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (35, 6, 'Nguyệt ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (36, 6, 'Nhật ấn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (37, 4, 'Số lần đã ký gửi #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (38, 5, 'Chỉ có tác dụng khi hợp thể');
insert into `optionitem` (`id`, `type`, `name`) VALUES (39, 6, '<Cập nhật bản mới để xem>');
insert into `optionitem` (`id`, `type`, `name`) VALUES (40, 7, 'Siêu cải trang # đá ngũ sắc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (41, 7, 'Chỉ số thưởng +#:');
insert into `optionitem` (`id`, `type`, `name`) VALUES (42, 7, 'Tấn công+#% lên quái bay');
insert into `optionitem` (`id`, `type`, `name`) VALUES (43, 7, 'Tấn công+#% lên quái khỉ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (44, 7, 'Tấn công+#% lên quái mặt đất');
insert into `optionitem` (`id`, `type`, `name`) VALUES (45, 7, 'Tấn công+#% lên tộc Namếc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (46, 7, 'Tấn công+#% lên tộc Trái đất');
insert into `optionitem` (`id`, `type`, `name`) VALUES (47, 0, 'Giáp+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (48, 2, 'HP, KI+#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (49, 1, 'Tấn công+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (50, 1, 'Sức đánh+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (51, 0, 'Sôn Gô Ku ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (52, 0, 'Ca Đic siêu ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (53, 0, 'Broly');
insert into `optionitem` (`id`, `type`, `name`) VALUES (54, 0, 'Mr. Santa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (55, 0, 'Broly ss#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (56, 0, 'Ca Lích');
insert into `optionitem` (`id`, `type`, `name`) VALUES (57, 0, 'Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (58, 0, 'Pic');
insert into `optionitem` (`id`, `type`, `name`) VALUES (59, 0, 'Siêu na mếc #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (60, 0, 'Sôn Gô Tên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (61, 0, 'Sôn Gô Ku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (62, 2, 'Phục hồi thể lực #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (63, 0, 'Còn lại # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (64, 0, 'Còn lại # giờ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (65, 0, 'Còn lại # phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (66, 0, 'Chưa có');
insert into `optionitem` (`id`, `type`, `name`) VALUES (67, 0, 'Dùng nâng cấp găng tay');
insert into `optionitem` (`id`, `type`, `name`) VALUES (68, 0, 'Dùng để nâng cấp áo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (69, 0, 'Dùng để nâng cấp quần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (70, 0, 'Dùng để nâng cấp giày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (71, 0, 'Dùng để nâng cấp rađa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (72, 0, 'Cấp #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (73, 0, '');
insert into `optionitem` (`id`, `type`, `name`) VALUES (74, 0, 'Dùng để ép thành đá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (75, 0, 'Dùng để làm phép');
insert into `optionitem` (`id`, `type`, `name`) VALUES (76, 0, 'Vip');
insert into `optionitem` (`id`, `type`, `name`) VALUES (77, 0, 'HP+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (78, 0, 'Sức hủy diệt+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (79, 0, 'Đệ tử #% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (80, 0, 'HP+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (81, 0, 'KI+#%/30s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (82, 0, 'Không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (83, 0, 'Tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (84, 0, 'Dùng để bay không tốn KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (85, 0, 'Dùng để bay và phục hồi KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (86, 0, 'Ký gửi vàng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (87, 0, 'Ký gửi ngọc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (88, 0, 'Cộng #% exp khi đánh quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (89, 0, 'Dùng để bay và phục hồi HP, KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (90, 0, 'Tặng cho người khác (bỏ ra đất) sẽ được nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (91, 0, 'Mở ra để nhận may mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (92, 0, 'Chúc tết bang hội và mọi người kèm theo pháo hoa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (93, 0, 'HSD # ngày');
insert into `optionitem` (`id`, `type`, `name`) VALUES (94, 0, 'Giảm #% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (95, 0, 'Biến #% tấn công thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (96, 0, 'Biến #% tấn công thành KI');
insert into `optionitem` (`id`, `type`, `name`) VALUES (97, 0, 'Phản #% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (98, 0, 'Xuyên giáp #% chưởng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (99, 0, 'Xuyên giáp #% cận chiến');
insert into `optionitem` (`id`, `type`, `name`) VALUES (100, 0, '+#% vàng rơi');
insert into `optionitem` (`id`, `type`, `name`) VALUES (101, 0, '+#% tiềm năng, sức mạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (102, 0, '# Sao Pha Lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (103, 0, 'KI +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (104, 0, 'Biến #% tấn công quái thành HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (105, 0, 'Vô hình khi không đánh quái và boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (106, 0, 'Chống lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (107, 0, '# Sao Pha Lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (108, 0, '#% Né đòn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (109, 0, 'Hôi, giảm #% HP');
insert into `optionitem` (`id`, `type`, `name`) VALUES (110, 0, 'Dò pha lê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (111, 0, 'Phân tâm');
insert into `optionitem` (`id`, `type`, `name`) VALUES (112, 0, 'Giảm #% khi mua Avatar hoặc Cải trang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (113, 0, 'Ném cho Sói Hẹc Quyn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (114, 0, '+#% TĐ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (115, 0, 'Biến cà rốt');
insert into `optionitem` (`id`, `type`, `name`) VALUES (116, 0, 'Kháng TDHS');
insert into `optionitem` (`id`, `type`, `name`) VALUES (117, 0, 'Đẹp: bản thân và người xung quanh tăng sức đánh +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (118, 0, 'Tới ngay mục tiêu và gây choáng trong # mili giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (119, 0, 'Gây mù xung quanh trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (120, 0, 'Ra đòn sau # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (121, 0, 'Ru ngủ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (122, 0, 'Bảo vệ trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (123, 0, 'Trói gô mục tiêu trong # giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (124, 0, 'Tỉnh giấc bị yếu đi -#% sức đánh trong 10 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (125, 0, 'Tăng và hồi phục #% HP tạm thời cho mình và xung quanh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (126, 0, 'Biến sôcôla làm yếu đi -#% sức đánh trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (127, 0, 'Set Thên Xin Hăng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (128, 0, 'Set Kirin');
insert into `optionitem` (`id`, `type`, `name`) VALUES (129, 0, 'Set Sôngôku');
insert into `optionitem` (`id`, `type`, `name`) VALUES (130, 0, 'Set Picolo');
insert into `optionitem` (`id`, `type`, `name`) VALUES (131, 0, 'Set Ốc tiêu');
insert into `optionitem` (`id`, `type`, `name`) VALUES (132, 0, 'Set Pikkoro Daimao');
insert into `optionitem` (`id`, `type`, `name`) VALUES (133, 0, 'Set Kakarot');
insert into `optionitem` (`id`, `type`, `name`) VALUES (134, 0, 'Set Ca Đíc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (135, 0, 'Set Nappa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (136, 9, '$(5 món +100% sát thương đấm Galick)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (137, 9, '$(5 món x5 thời gian hóa khỉ)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (138, 9, '$(5 món +80% HP)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (139, 9, '$(5 món x2 thời gian chói mắt)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (140, 9, '$(5 món +100% sát thương Quả Cầu Kênh Khi)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (141, 9, '$(5 món +100% sát thương Kamejoko)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (142, 9, '$(5 món +50% sát thương Masenkosappo)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (143, 9, '$(5 món Bất tử xung quanh khi đánh quái)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (144, 9, '$(5 món +100% sát thương và bất tử đệ từ Đẻ Trứng)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (145, 0, '$(Ở gần 1 CT Dr Slum khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (146, 0, '$(Ở gần 2 CT Dr Slum khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (147, 0, '+#% sức đánh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (148, 0, '+#% tốc độ chạy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (149, 0, '(Chỉ số tăng khi ở gần CT Hải Tặc khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (150, 0, '(Chỉ số tăng khi ở gần Android Sát Thủ khác loại)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (151, 0, '$(Ở gần 1 CT nhóm Piláp khác loại +20% sức đánh +66% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (152, 0, '$(Ở gần 2 CT nhóm Piláp khác loại +30% sức đánh +100% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (153, 0, '#% tỉ lệ phát nổ sau khi chết');
insert into `optionitem` (`id`, `type`, `name`) VALUES (154, 0, 'Không thể bán lại');
insert into `optionitem` (`id`, `type`, `name`) VALUES (155, 0, 'Giảm 50% sức đánh, HP, KI và +#% SM, TN, vàng từ quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (156, 0, 'Cộng dồn 1% sức đánh khi chỉ dùng chiêu đấm, tối đa #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (157, 0, 'Giảm #% mọi sát thương khi KI dưới 20%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (158, 0, 'Khi ở trần và không đeo cải trang sẽ có cơ hội tìm thấy vật phẩm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (159, 0, 'x# sức đánh đòn chưởng cơ bản mỗi phút');
insert into `optionitem` (`id`, `type`, `name`) VALUES (160, 0, '+#% TN, SM cho đệ tử khi sư phụ mặc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (161, 0, 'Thêm # ngọc mỗi ngày khi đánh quái.');
insert into `optionitem` (`id`, `type`, `name`) VALUES (162, 0, 'Cute hồi #% KI/s bản thân và xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (163, 0, 'Biến người xung quanh thành Bí Ngô');
insert into `optionitem` (`id`, `type`, `name`) VALUES (164, 0, 'Đổi bằng # điểm sự kiện');
insert into `optionitem` (`id`, `type`, `name`) VALUES (165, 0, 'Cơ hội ra đòn +#% sát thương lửa khi cận chiến quái');
insert into `optionitem` (`id`, `type`, `name`) VALUES (166, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy');
insert into `optionitem` (`id`, `type`, `name`) VALUES (167, 0, 'Tạo không khí lạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (168, 0, 'Hấp thụ sức mạnh rồi bộc phá');
insert into `optionitem` (`id`, `type`, `name`) VALUES (169, 0, 'Cơ hội hạ độc đối thủ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (170, 0, 'Ngầu +#% sức đánh lên quái khi bay với Cải Trang nhà Fide');
insert into `optionitem` (`id`, `type`, `name`) VALUES (171, 0, 'Số lượng #K');
insert into `optionitem` (`id`, `type`, `name`) VALUES (172, 0, '#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (173, 0, 'Phục hồi #% HP và KI cho đồng đội');
insert into `optionitem` (`id`, `type`, `name`) VALUES (174, 0, 'Sự kiện năm #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (175, 0, 'Giảm #% thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (176, 0, '$(Ở gần đủ 5 loại +20% sức đánh +50% tốc độ chạy)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (177, 0, '$(Tối đa +2% tất cả khi ở gần Mabư mập)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (178, 0, 'KI+#%/10s');
insert into `optionitem` (`id`, `type`, `name`) VALUES (179, 0, '+2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost');
insert into `optionitem` (`id`, `type`, `name`) VALUES (180, 0, '+#% sức đánh khi ở gần Cải Trang Black Gohan Rose');
insert into `optionitem` (`id`, `type`, `name`) VALUES (181, 0, 'Dịch chuyển tức thời +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (182, 0, '+#% sát thương đệ từ trứng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (183, 0, 'Giảm #% thời gian hồi Khiên');
insert into `optionitem` (`id`, `type`, `name`) VALUES (184, 0, '+#% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê');
insert into `optionitem` (`id`, `type`, `name`) VALUES (185, 0, '+# giờ sử dụng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (186, 0, 'Biến kẹo 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (187, 0, 'Giảm # giây thời gian bị mù');
insert into `optionitem` (`id`, `type`, `name`) VALUES (188, 0, 'Đệ tử chưởng kamejoko +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (189, 0, 'Đệ tử chưởng antomic +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (190, 0, 'Đệ tử chưởng masenko +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (191, 0, 'Né chí mạng+#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (192, 0, '+#% Chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (193, 0, '+#% sức đánh, tối đa 11% khi ở gần Cải trang cầu thủ khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (194, 0, '+#% sức đánh, tối đa 10% khi ở gần Cải trang hè khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (195, 0, '+#% sức đánh, tối đa 10% khi ở gần Cải trang siêu nhân khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (196, 0, 'Xinh +#% sức đánh, tối đa 18% khi ở gần Cải trang Thỏ khác');
insert into `optionitem` (`id`, `type`, `name`) VALUES (197, 7, 'Tấn công+#% lên tộc Xayda');
insert into `optionitem` (`id`, `type`, `name`) VALUES (198, 7, 'Giảm #% sát thương từ tộc Trái Đất');
insert into `optionitem` (`id`, `type`, `name`) VALUES (199, 7, 'Giảm #% sát thương từ tộc Namếc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (200, 7, 'Giảm #% sát thương từ tộc Xayda');
insert into `optionitem` (`id`, `type`, `name`) VALUES (201, 7, 'Tấn công+#% gần 2 thành viên bang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (202, 7, 'HP+#% gần 2 thành viên bang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (203, 7, 'KI+#% gần 2 thành viên bang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (204, 7, 'Tấn công+#% lên Boss');
insert into `optionitem` (`id`, `type`, `name`) VALUES (205, 7, 'Đi cùng CT Diệt Quỷ +#% SĐ, tối đa 18%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (206, 0, 'Vật phẩm hiếm rơi từ quái (+#%)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (207, 0, 'Vật phẩm hiếm rơi từ boss (+#%)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (208, 0, 'Trang bị đã chuyển hóa');
insert into `optionitem` (`id`, `type`, `name`) VALUES (209, 0, 'Bị rớt cấp # lần');
insert into `optionitem` (`id`, `type`, `name`) VALUES (210, 0, '# Dòng chỉ số ẩn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (211, 0, 'Giám định #/5');
insert into `optionitem` (`id`, `type`, `name`) VALUES (212, 0, 'Độ bền #/1000');
insert into `optionitem` (`id`, `type`, `name`) VALUES (213, 0, 'Giá bán: # triệu vàng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (214, 0, 'Phạm vi tuyệt kỹ +#%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (215, 0, 'Số lượng mục tiêu +#');
insert into `optionitem` (`id`, `type`, `name`) VALUES (216, 0, 'Tuyệt kỹ +#% sát thương');
insert into `optionitem` (`id`, `type`, `name`) VALUES (217, 0, '- Chưa giám định');
insert into `optionitem` (`id`, `type`, `name`) VALUES (218, 0, ' ---------');
insert into `optionitem` (`id`, `type`, `name`) VALUES (219, 0, 'Số lần tẩy #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (220, 0, 'Hoàn thành #%');
insert into `optionitem` (`id`, `type`, `name`) VALUES (221, 0, 'Phục hồi #% HP và  KI mỗi 30 giây cho bản thân và đồng bang');
insert into `optionitem` (`id`, `type`, `name`) VALUES (222, 0, '120 giây kích nộ sức đánh #% trong 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (223, 0, '120 giây kích hồi #% HP trong vòng 30 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (224, 0, 'Giảm thời gian cooldown của tất cả kỹ năng về 0,1 giây');
insert into `optionitem` (`id`, `type`, `name`) VALUES (225, 0, 'Giảm # giây bị phong ấn của Ma Phong Ba');
insert into `optionitem` (`id`, `type`, `name`) VALUES (226, 0, 'Cute +#% SĐ cho mình và người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (227, 0, 'Giảm #% tác dụng của các đòn khống chế khi dùng khiên năng lượng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (228, 0, 'Cường hóa tới ô sao pha lê #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (229, 0, 'Lạnh gây giảm #% HP , KI mỗi 30s cho những người xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (230, 0, '+# triệu tiềm năng, sức mạnh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (231, 0, 'Hạn sử dụng hoặc vĩnh viễn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (232, 0, 'Số lần giao dịch còn lại: #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (233, 0, 'Set Gohan');
insert into `optionitem` (`id`, `type`, `name`) VALUES (234, 9, '$(5 món +150% may mắn +30% vàng rơi từ quái)');
insert into `optionitem` (`id`, `type`, `name`) VALUES (235, 0, 'Số lần ký gửi còn lại: #');
insert into `optionitem` (`id`, `type`, `name`) VALUES (236, 0, '+#% May mắn');
insert into `optionitem` (`id`, `type`, `name`) VALUES (237, 0, 'Set Nail chiến binh Namếc');
insert into `optionitem` (`id`, `type`, `name`) VALUES (238, 10, '$[2] Tăng nhẹ sát thương chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (239, 10, '$[4] Giảm nhẹ hồi chiêu Masenko');
insert into `optionitem` (`id`, `type`, `name`) VALUES (240, 10, '$[5] Tăng sát thương Masenko, giảm mạnh hồi chiêu Masenko');
insert into `optionitem` (`id`, `type`, `name`) VALUES (241, 0, 'Set Cađic M');
insert into `optionitem` (`id`, `type`, `name`) VALUES (242, 10, '$[2] Tăng nhẹ HP và phạm vi ảnh hưởng chiêu phát nổ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (243, 10, '$[4] Tăng nhẹ sát thương chiêu phát nổ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (244, 10, '$[5] Tăng mạnh sát thương chiêu phát nổ');
insert into `optionitem` (`id`, `type`, `name`) VALUES (245, 0, 'Set Thần Vũ Trụ Kaio');
insert into `optionitem` (`id`, `type`, `name`) VALUES (246, 10, '$[2] Tăng mạnh chí mạng');
insert into `optionitem` (`id`, `type`, `name`) VALUES (247, 10, '$[4] Giảm nhẹ hao HP,KI chiêu Kaioken');
insert into `optionitem` (`id`, `type`, `name`) VALUES (248, 10, '$[5] Tăng mạnh sát thương và giảm mạnh hao HP,KI chiêu Kaioken');
insert into `optionitem` (`id`, `type`, `name`) VALUES (249, 0, 'Hắc hóa: +#% HP cho người chơi xung quanh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (250, 0, 'Cool: +#% sức đánh bản thân và đồng minh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (251, 0, 'Hồi HP +#%/10s cho bản thân và đồng minh');
insert into `optionitem` (`id`, `type`, `name`) VALUES (252, 0, 'Test 252');
insert into `optionitem` (`id`, `type`, `name`) VALUES (253, 0, 'Test 253');
insert into `optionitem` (`id`, `type`, `name`) VALUES (254, 0, 'Test 254 +#');
